config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spades
  get '/spades_wizard/new' => 'spades#new_wizard', as: :new_wizard
  post '/spades_wizard/new' => 'spades#new_wizard_save', as: :new_wizard_save
  get '/spades/:id/wizard/:step' => 'spades#wizard_step', as: :wizard_step
  patch '/spades/:id/wizard/:step' => 'spades#wizard_save', as: :wizard_step_save

  get '/logic/:this/then/:that' => 'logic#if_this_then_that', as: :if_this_then_that

  root to: 'spades#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spade.rb
class Spade < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protected

  def ctx
    { params: params.to_unsafe_h }
  end
end

app/controllers/logic_controller.rb
class LogicController < ApplicationController
  def if_this_then_that
    # Activity call signature return value:
    # signal, [ctx] = Logic::Operation::CheckAnimal.(ctx)
    signal, result = Logic::Operation::CheckAnimal.(ctx)
    @found = "Signal: #{signal.to_h[:semantic].capitalize}"
    @result = result[0][:sound]
    unless result[0][:exception_class].nil?
      @exception = "Neatly handled an exception: #{result[0][:exception_class]}"
    end
  end
end

app/controllers/spades_controller.rb
class SpadesController < ApplicationController

  def show
    @spade = Spade.find_by(id: params[:id])
    unless @spade
      redirect_to spades_path, alert: 'Spade not found'
    end
  end

  def new
    result = Spade::Operation::New.(ctx)
    @spade_form = result[:'contract.default']
  end

  def create
    result = Spade::Operation::Create.(ctx)
    @spade_form = result[:'contract.default']
    if result.success?
      redirect_to result[:model], alert: 'Spade created'
      return
    end
    render 'new'
  end

  def new_wizard
    result = Spade::Operation::NewWizard.(ctx)
    @spade_wizard = result[:'contract.default']
    @spade_wizard.step = 0
  end

  def new_wizard_save
    result = Spade::Operation::CreateWizard.(ctx)
    @spade = result[:model]
    if result.success?
      @spade_wizard = result[:'contract.default']
      redirect_to wizard_step_path(id: @spade.id, step: 1)
      return
    end
    @spade_wizard = result[:'contract.default']
    @spade_wizard.step = 0
    render 'new_wizard'
  end

  def wizard_step
    step = params[:step].to_i
    result = Spade::Operation::WizardStep.call(ctx)
    @spade_wizard = result[:'contract.default']
    @spade_wizard.step = step
    if result.success?
      if @spade_wizard.is_ready?
        redirect_to result[:model], alert: 'Spade completed'
        return
      end
      render 'wizard'
      return
    end
    redirect_to spades_path, alert: 'Spade not found'
  end

  def wizard_save
    step = params[:step].to_i
    result = Spade::Operation::UpdateWizard.call(ctx)
    @spade = result[:model]
    @spade_wizard = result[:'contract.default']
    @spade_wizard.step = step + 1
    if result.success? and @spade_wizard.is_ready?
      redirect_to @spade
      return
    end
    redirect_to wizard_step_path(id: @spade_wizard.model.id, step: step + 1)
  end

  def edit
    result = Spade::Operation::Edit.call(ctx)
    unless result.success?
      redirect_to spades_path, alert: 'Spade not found'
      return
    end
    @spade_form = result[:'contract.default']
  end

  def update
    result = Spade::Operation::Update.call(ctx)
    @spade = result[:model]
    if result.success?
      redirect_to @spade
      return
    end
    @spade_form = result[:'contract.default']
    render 'edit'
  end

  def index
    ctx = {params: {}}
    Spade::Operation::Index.([ctx, {}], {})
    @spades = ctx[:spades]
  end

  def destroy
    result = Spade::Operation::Destroy.call(ctx)
    if result.success?
      redirect_to spades_path
    else
      redirect_to result[:model]
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spades_helper.rb
module SpadesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = Shovel
  = csrf_meta_tags
  = csp_meta_tag

  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      - flash.each do |type, msg|
        = msg
      = yield

app/views/logic/if_this_then_that.html.slim
h5 Result
p = @result
p = @found
p = @exception
br
.row
  .col-2
    = Component::Button::render(if_this_then_that_path('dog', 'bark'), 'Dog -> Bark')
  .col-2
    = Component::Button::render(if_this_then_that_path('cow', 'moo'), 'Cow -> Moo')
  .col-2
    = Component::Button::render(if_this_then_that_path('stone', 'exception'), 'Stone -> Exception')
  .col-2
    = Component::Button::render(if_this_then_that_path('bat', 'flap'), 'Bat -> --')
  .col-2
    = Component::Button::render(if_this_then_that_path('rex', 'extinct'), 'Rex -> --')
.row
  .col-2
    = Component::Button::render(spades_path, 'Back to Spades')

app/views/spades/edit.html.slim
h1 Edit Spade
= render html: cell(Spade::Cell::Form, @spade_form )

app/views/spades/index.html.slim
= render html: cell(Spade::Cell::Index, @spades)
= Component::Button::render(if_this_then_that_path('dog', 'woof'), 'Logic checker')

app/views/spades/new.html.slim
h1 New Spade
= render html: cell(Spade::Cell::Form, @spade_form)

app/views/spades/new_wizard.html.slim
h1 New wiz...
= render html: cell(Spade::Cell::FormStep, @spade_wizard)

app/views/spades/show.html.slim
= render html: cell(Spade::Cell::Show, @spade, spade_form: @spade_form)
= button_to 'all', spades_path, method: :get, class: 'm-2 btn btn-info'

app/views/spades/wizard.html.slim
h1 Wiz...
= render html: cell(Spade::Cell::FormStep, @spade_wizard)